Signed links
eluv-io/elv-client-js pull request #170
Opened 2022-08-23 21:13 UTC by elv-zenia

Add CreateSignedLink method to append an authorization token to an existing link.

2022-08-23 21:20 UTC, elv-kevin requested changes

2022-08-23 21:20 UTC, elv-kevin commented on src/client/ContentManagement.js
> + * @param {Array<Object>} links - Link specifications
param definition for link doesn't match implementation

2022-08-23 21:20 UTC, elv-kevin commented on src/client/ContentManagement.js
> +exports.CreateSignedLink = async function({
this method shouldn't be for updating existing links. it should create a link if not present, or overwrite the existing one appropriately (making sure extra unrelated fields in the link are preserved)

2022-08-23 21:20 UTC, elv-kevin commented on src/AuthorizationClient.js
> +    const signerAddress = (this.client.signer && this.client.signer.address) || "";
use this.client.CurrentAccountAddress()

https://eluv-io.github.io/elv-client-js/ElvClient.html#CurrentAccountAddress

2022-08-24 20:28 UTC, elv-zenia commented
@elv-kevin Updated

2022-11-03 19:59 UTC, elv-zenia commented
@elv-kevin I updated `CreateLinks` based on current usage, which just cares about putting link metadata directly into a specified path. But since assets go in a path like `index`/`slug`/`link`, I made it so that the client is responsible for providing the right path.

2022-11-21 20:43 UTC, merged